run-name: ${{ github.actor }} opened a pull request
on: [ pull_request ]
jobs:
  setup-shrink-sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Infra Setup
        run: |
          printf '1\n1\n' | make
          echo "CONTAINER_COUNT=$(docker inspect shrink-sync-network | grep Name | wc -l)" >> $GITHUB_ENV     
      
      - name: Test Setup    
        if: env.CONTAINER_COUNT != 5 
        run: |
          echo "All the 4 Containers are not created, Created container are $(CONTAINER_COUNT)!!"
          exit 1
